### ISSUE TITLE
Change twitter logo to X in readme file

### ISSUE THREAD

**Issue by dalvishruti14** [learn-anything/learn-anything.xyz#34]
The current Twitter logo used in the project needs to be updated to a new logo represented by 'X'.
I would like to work on this

**Comment by nikitavoloboev** [comment]
Sure you can propose a badge that looks as clean but with X logo. Would be nice.

**Comment by dalvishruti14** [comment]
okay will do

**Comment by dalvishruti14** [comment]
@nikitavoloboev please review this
